ERMD test
PHOTOX/ABIN pull request #120
Opened 2022-04-22 14:04 UTC by suchanj

Energy constraint MD minor refactor + test suite. Testing both Lagrange multipliers and quadratic restraint, _tera_ option not tested. Also output redirected to dedicated file, unfortunately one need to keep the en_restraint variable in mod_general to be able to initialize the file. There is still more work to be done, but should suffice for now.

2022-04-22 14:36 UTC, suchanj commented
Interestingly, intel compiler could not handle diff of header >80 characters.

2022-04-22 23:47 UTC, danielhollas requested changes
Amazing, thanks so much! I left just a couple of minor comments. I will take a closer look on Monday but it looks good!

Yeah, intel compiler is super annoying with the long lines. At least the test suite caugh it! 🎉 Took me a long time to make all the tests work, so I am glad it is paying dividends. :-)

2022-04-22 23:47 UTC, danielhollas commented on src/en_restraint.F90
> +            !write (*, *) 'Lambda multiplier:', lambda
I would remove the commented out write statements to keep the code clean. Should be easy to write them back if needed. Alternatively, you can uncomment them and only print if `idebug > 0`

2022-04-22 23:47 UTC, danielhollas commented on src/en_restraint.F90
> +            !-----READING energy of groud state (engrad.ground.dat)
Could you please change open (901, ... To open (newunit=u,...

2022-04-22 23:47 UTC, danielhollas commented on tests/ERMD/input.in
> +natom=5,		!number of atoms
Natom in the input file is deprecated and does not have any effect. Same with imini

2022-04-25 07:21 UTC, danielhollas requested changes
Couple of additional minor comments. Thanks!

2022-04-25 07:21 UTC, danielhollas commented on src/en_restraint.F90
>     public
Could you please make the module private and list public subroutines / variables explicitly?
```suggestion
   private
   public :: en_rest_init, energy_restraint
   public :: en_diff, en_kk, restrain_pot
```

2022-04-25 07:21 UTC, danielhollas commented on src/en_restraint.F90
> +            !-----READING energy of groud state (engrad.ground.dat)
Alternatively, it would be nice to reuse the new functions from force_abin() for reading energies and forces, it would simplify the code here. But feel free to skip this suggestion.

2022-04-25 07:21 UTC, danielhollas commented on src/en_restraint.F90
> +            write (formt, '(A30)') '(I8,F16.8,E20.10,E20.10,F16.8)'
This `formt` and the same below seems unnecessary, you can just put the format string directly into the actual write statement.

2022-04-25 07:21 UTC, danielhollas commented on src/en_restraint.F90
> +   subroutine en_rest_finalize()
Thanks for making this!

2022-04-25 07:21 UTC, danielhollas commented on src/init.F90
> +      use mod_en_restraint, only: en_rest_init, en_diff, en_kk, restrain_pot
Thank you for being explicit here. :+1:

2022-04-25 07:21 UTC, danielhollas commented on tests/ERMD/input.in
> +This is a sample input file for ABIN for CMD simulation
Remove this comment line or update it to explain what it does.

2022-04-25 07:21 UTC, danielhollas commented on tests/ERMD/input.in
> +
Please remove the lines below.

2022-04-25 07:21 UTC, danielhollas commented on src/en_restraint.F90
> +   use mod_const, only: DP, AUTOEV
At the beginning of the module, could you please make a short comment explaining what it does? At the very least, please include the reference for the Faraday paper (personally I like to have a direct DOI URL, `https://doi.org/<doi_number>`)

2022-04-25 08:34 UTC, suchanj commented
Thanks for the suggestions, all included, definitely improved the code.

2022-04-25 10:51 UTC, danielhollas approved these changes

2022-04-25 11:25 UTC, merged

2022-04-25 11:30 UTC, danielhollas commented
Thanks @suchanj!

2022-04-25 11:57 UTC, danielhollas commented
@suchanj I just noticed that after running the ERMD test, there are two extra files left, `tests/ERMD/engrad.exc.dat.001` and `tests/ERMD/engrad.ground.dat.001`, even though you are deleting them after reading them in the energy_restrain subroutine. 
The culprit is that in the verletstep, you're calling the `energy_restrain` only after the first `shiftP()` call, and not after the second one. I wonder whether that is correct?

2022-04-25 12:19 UTC, suchanj commented
Damn it. I did some numerical tests and the current setup seems to perform the best. We should therefore remove the delete flag from close command and move it to the finalize routine ...

2022-04-25 12:52 UTC, danielhollas commented
I'd keep the delete status where it is, it is best to delete the file as soon as it is read, otherwise one risks that incorrect file is read in the next step if the external program fails. Maybe for now we can only add the files to .gitignore, it's not a huge deal. 

I do wonder about the validity of the code. Generally in Verlet integrator, one should perform velocity modifications after each shiftP, this is e.g. how thermostats and SHAKE are implemented. Anyways, just something to think about in case we'd end up using it again. :-)

2022-04-25 12:58 UTC, suchanj commented
Ok, lets keep it that way.

I'm also bit uncertain about the validity. We should definitely review the procedure before further usage :+1: