BAGEL interface for XMS and MS-CASPT2 in FSSH and LZSH
PHOTOX/ABIN pull request #153
Opened 2022-12-01 15:18 UTC by JanosJiri

The interface for BAGEL and ABIN to perform FSSH and LZSH simulations. It is set to do XMS-CASPT2 by default but input can be modified for MS-CASPT2 and CASSCF. It was tested on cyclopropanone molecule and benchmarked to MOLPRO. Credits to Tomas Jira and Jiri Suchan.

2022-12-01 16:39 UTC, danielhollas requested changes
Awesome, thanks so much to all who contributed to this interface! :+1:

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel
> +/home/srsen/bin/anaconda3/bin/mpirun -np 1 BAGEL $input.json > $input.out
Use the `SetEnvironment.sh` paradigm, take a look how it is done in the other interfaces. I would suggest to define the following two variables there:

```sh
export PATH=path/to/bagel:$PATH
BAGELEXE=BAGEL
MPIRUN=/home/srsen/bin/anaconda3/bin/mpirun
```

So then the line will be

```sh
source SetEnvironment.sh BAGEL
$MPIRUN -np $nproc $BAGELEXE $input.json &> $input.out
```
with `nproc` defined with all the other parameters.

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel
> +if $( grep -q 'ERROR: EXCEPTION RAISED:  Max iteration reached during the second-order optimization.' $input.out ) ;then
```suggestion
if `grep -q 'ERROR: EXCEPTION RAISED:  Max iteration reached during the second-order optimization.' $input.out` ;then 
```

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel
> +cat ENERGY.out >> ../engrad.dat.$ibead
```suggestion
cat ENERGY.out > ../engrad.dat.$ibead
```

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel
> +let natom1=natom+1
Delete these unused variables.

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-SH/r.bagel
> +# Definition of wavefunction
Apply suggestions from `BAGEL-LZ/r.bagel-lz`

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-SH/r.bagel
> +#!/bin/bash
Rename file to `r.bagel-sh`

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel
> +#!/bin/bash
Rename file to `r.bagel-lz`

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-SH/r.bagel.nacm
> +#!/bin/bash
Rename to `r.bagel-sh.nacm`

2022-12-01 16:39 UTC, danielhollas commented on interfaces/BAGEL-SH/r.bagel.nacm
> +
Check the return value of this command, look how it is done in other interfaces.

```sh
if [[ $? -ne 0 ]];then
    echo "BAGEL exited with error. Check $input.out"
    exit 2
fi
```

2022-12-01 17:19 UTC, JanosJiri commented on interfaces/BAGEL-LZ/r.bagel
> +#!/bin/bash
Done

2022-12-08 20:24 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel
> +if $( grep -q 'ERROR: EXCEPTION RAISED:  Max iteration reached during the second-order optimization.' $input.out ) ;then
I have confused myself here. `$(command)` and `` `command` `` are essentially equivalent. They are called [command substitution](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html), and return the standard output (stdout) of the command. But `grep -q` will never print anything into its stdout anyway.

What we instead want to be testing is the _return value_ (or exit status) of the command. In linux, successful execution should always return 0, which (somewhat confusingly) is evaluated as true by the if statement. Anything other than 0 is false. One can check that by looking at the return values of the `false` and `true` commands.

```
$ /bin/true; echo $?
0
$ /bin/false; echo $?
1
```

You can also checkout the `EXIT STATUS` section of grep's manpage.

The original code still works, because the return value of the command substitution is the return value of the command itself. But it is superfluous, one can simply write

```
if grep -q 'ERROR: ...' $input.out; then

fi
```

Here's a little comic about various brackets in BASH that I found extremely useful.
https://wizardzines.com/comics/brackets-cheatsheet/

CC @JanosJiri

2023-01-26 14:11 UTC, danielhollas commented
@JanosJiri is this ready for a new round of review or not yet?

2023-01-26 15:02 UTC, JanosJiri commented
Yes, it's ready for review @danielhollas.

2023-01-26 17:59 UTC, danielhollas requested changes
This is looking great now @JanosJiri! Some final small things, and then I'll test it locally with our BAGEL.

2023-01-26 17:59 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel-lz
> +cat ENERGY.out >> ../engrad_all.dat
```suggestion
cat ENERGY.out > ../engrad.dat.$ibead
cat ENERGY.out > ../engrad_all.dat
```

2023-01-26 17:59 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel-lz
> +    atom=$(echo $(cat ../geom.dat.$ibead | head -n $j | tail -n 1) | awk '{print $1}')
Please simplify all of this with AWK. Something like this should work

```awk
awk -v natom="$natom" ' \
{printf('{ "atom" : %d, "xyz" : [ %.15f, %.15f, %.15f]}", natom, $1, $2, $3} \
NR != natom {print ","}
'
```

2023-01-26 17:59 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel-lz
> +    atom=$(echo $(cat ../geom.dat.$ibead | head -n $j | tail -n 1) | awk '{print $1}')
Please rewrite this with AWK, something like this should work

```awk
awk -v natom="$natom" '{printf "{ \"atom\" : %s, \"xyz\" : [ %.15f, %.15f, %.15f]}", $1, $2, $3, $4} NR != natom {print ","}END{print ""}'  ../geom.dat.$ibead >> $input.json
```

2023-01-26 17:59 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel-lz
> +#!/bin/bash
Please apply comments on this file to the files in BAGEL-SH as well.

2023-01-26 17:59 UTC, danielhollas commented on interfaces/BAGEL-LZ/r.bagel-lz
> +/home/srsen/bin/anaconda3/bin/mpirun -np 1 BAGEL $input.json > $input.out
Also it would be really great to get rid of this hard-coded path and use the SetEnvironment.sh approach. Note that here we also assume that BAGEL is in $PATH.

2023-03-01 14:20 UTC, JanosJiri commented on interfaces/BAGEL-LZ/r.bagel-lz
> +    atom=$(echo $(cat ../geom.dat.$ibead | head -n $j | tail -n 1) | awk '{print $1}')
Done

2023-03-02 16:15 UTC, JanosJiri commented on interfaces/BAGEL-LZ/r.bagel-lz
> +/home/srsen/bin/anaconda3/bin/mpirun -np 1 BAGEL $input.json > $input.out
Done, ready for review.

2023-03-02 16:53 UTC, danielhollas commented
Thanks @JanosJiri :clap: I'll do some testing locally (hopefully next week) and then we should be good to go!

2023-11-30 21:07 UTC, danielhollas commented
@JanosJiri I've cleaned up the interfaces in BAGEL-SH and tested XMS-CASPT2, MS-CASPT2 and CASSCF. I've been able to reduce a lot of duplication by moving stuff into functions in bagel.inp. If this looks good to you I'll apply the same thing to LZ and ground state BAGEL.

2023-12-01 15:51 UTC, JanosJiri commented on interfaces/BAGEL-SH/r.bagel-sh
> +cat >> $input.json << EOF
You have a fucntion in bagel.inp to do this if I understood it correctly.

2023-12-12 18:26 UTC, danielhollas commented
Okay, I think I am done. :sweat_smile: I've cleaned up all the three interfaces and tested them on Hamilton. The scripts now also pass the `shellcheck` [BASH linter](https://www.shellcheck.net/), invoked as

```
shellcheck -a -x r.bagel*
```

@JanosJiri It would be great if you could do last tests on Prague clusters and then we're good to go. When testing, you can increase the `deltaE` parameter so that you also exercise the NACM calculation. Thanks!

2024-01-15 14:43 UTC, danielhollas approved these changes
I am going to merge this. We can always open a new PR if we run into any issues or have more improvements. 

Awesome work, very happy with what we have. :clap:

2024-01-15 14:50 UTC, merged