Interface for Laundau-Zener SH with MNDO program
PHOTOX/ABIN pull request #155
Opened 2023-01-24 09:12 UTC by JanosJiri

This interface allows to run LZSH simulations with the OMx methods in the MNDO package. Tested for OM2, OM3, ODM2 and ODM3. Works only for states with the same multiplicity, ISC cannot be described. Contributions Michal Belina and Jan Polena.

2023-01-26 14:08 UTC, danielhollas requested changes
Thanks so much @JanosJiri et al. This is looking great! One important fix (adding an early exit when the MNDO program fails) and couple of very minor comments, feel free to ignore them.

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +cp ../engrad.dat.$ibead ../engrad.dat.$ibead.old
Not sure if this works? I believe new ABIN versions should delete the the engrad file as soon as it is read, so when this script is called, there should be no such file.

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +}
```suggestion
```

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +   cp $input.out $input.out.error
```suggestion
   cp $input.out $input.out.error
   exit 2
```

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +if [[ $? -ne 0 ]] || ! $( grep -q "COMPUTATION TIME" $input.out ) || ! $( grep -q "SCF TOTAL ENERGY" $input.out ) ;then
Nice! :clap:

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +		print $4;
nitpick
```suggestion
		print $4
```

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +grep 'State  ' $input.out | awk '{printf "%.8f\n\n", $9/27.211396}' > ../engrad.dat.$ibead
Does this precision "%.8f" correspond to the precision in the MNDO output file? (8 decimal places seem a bit low to me)

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +grep -A$(($natom*3))  'INTERNAL COORDINATES AND GRADIENTS'  fort.15 | tail -n +2 | awk '
Haha, the infamous `fort.xx` files. :rofl:

2023-01-26 14:08 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +	NR%3==1{gradx=$4*toAU}
Cool, nice use of AWK! :+1:

2023-02-01 08:52 UTC, JanosJiri commented on interfaces/MNDO-LZ/r.mndo-lz
> +cp ../engrad.dat.$ibead ../engrad.dat.$ibead.old
True, deleted

2023-02-01 08:56 UTC, JanosJiri commented on interfaces/MNDO-LZ/r.mndo-lz
> +}
Done

2023-02-01 08:58 UTC, JanosJiri commented on interfaces/MNDO-LZ/r.mndo-lz
> +		print $4;
Dipole moment was deleted since it is not necessary

2023-02-01 09:03 UTC, JanosJiri commented on interfaces/MNDO-LZ/r.mndo-lz
> +grep 'State  ' $input.out | awk '{printf "%.8f\n\n", $9/27.211396}' > ../engrad.dat.$ibead
MNDO's precision is 6 decimal places in eV, see below grep from the output
`State  1,  Mult. 1,  E-E(1)=  0.000000 eV,  E=  -2073.514397 eV`
It is converted to a.u. so 8 decimal places should be sufficient.

2023-02-01 09:04 UTC, JanosJiri commented on interfaces/MNDO-LZ/r.mndo-lz
> +natom=$(cat $geom | wc -l )
Done

2023-02-01 11:33 UTC, danielhollas approved these changes
Awesome, thanks @JanosJiri et al!

2023-02-01 11:33 UTC, danielhollas commented on interfaces/MNDO-LZ/r.mndo-lz
> +grep 'State  ' $input.out | awk '{printf "%.8f\n\n", $9/27.211396}' > ../engrad.dat.$ibead
I see, thanks.

2023-02-01 11:34 UTC, merged