Improvements of LZSH algortihm
PHOTOX/ABIN pull request #159
Opened 2023-04-12 07:13 UTC by JanosJiri

This commit slightly modifies the LZ code to fix issues we encountered for several molecules.

1. LZ is computed just for the neighbouring states, not all that are available. Previously, the implementation allowed for unphysical hops like S1 --> S4.
2. Warning is printed out when the sum of hopping probabilities to the two neighbouring states is larger than one. ABIN somehow deals with that but LZ formula is no longer valid and would need a 3-state generalization. 
3. Warning is printed out when possible discontinuities are encountered. It is based on second derivatives. Testing on azobenzene and bilirubin showed it is able to warn the user when hops due to discontinuity happen.
4. Warning at the beginning of output if there are more than two states of the same multiplicity. In such cases, LZ works only when the states are well separated. This doesn't hold true for azobenzene, bilirubin, porphyrin and other molecules and LZ should not be used.

Btw, the simple velocity rescaling right be also a problem for LZSH but this was not modified.

2023-04-12 14:58 UTC, danielhollas requested changes
Cool! These look like very important fixes. I mostly have just a couple of clarifying questions.
In general, don't be afraid to spell things out a bit more in the code comments to make things super-clear for anybody who might look at this code. Thanks!

(note, the tests are not running because of the old Ubuntu version, I am fixing that in #160

2023-04-12 14:58 UTC, danielhollas commented on src/landau_zener.F90
> +                if (der_check > 0.3) then
Can you make a comment about how you came to this threshold? If I understand the code correctly, does this check if the second derivative changes more than 30%? Please add an explanation to make this super-clear.

2023-04-12 14:58 UTC, danielhollas commented on src/landau_zener.F90
> +                    write (*,*) "WARNING, possible discontinuity in PES! Check PES.dat!"
This seems like a rather serious issue that may lead to false hops. Should we rather stop instead of just issuing the warning?

2023-04-12 14:58 UTC, danielhollas commented on src/landau_zener.F90
> +          write (*,*) "* WARNING, sum of hopping probabilities > 1. Breakdown of LZ assumptions"
```suggestion
          write (stdout, *) "WARNING: Sum of hopping probabilities > 1. Breakdown of LZ assumptions"
```

2023-04-12 14:58 UTC, danielhollas commented on src/landau_zener.F90
> +         write (fileunit, '(3ES25.16E3)') en_array_lz(ist, 1), en_array_lz(ist, 2), en_array_lz(ist, 3), en_array_lz(ist, 4)
This is a breaking change, right? Previous restart files will stop working after this?

2023-04-12 14:58 UTC, danielhollas commented on src/landau_zener.F90
> +         if (abs(en_diff(2) * AUTOEV) > deltaE_lz) cycle
Could you make the comment at the top of the file where `deltaE_lz` is specified that it is in eV?

2023-04-13 13:40 UTC, JanosJiri commented on src/landau_zener.F90
> +          write (*,*) "* WARNING, sum of hopping probabilities > 1. Breakdown of LZ assumptions"
Done

2023-04-13 13:55 UTC, JanosJiri commented on src/landau_zener.F90
> +         if (abs(en_diff(2) * AUTOEV) > deltaE_lz) cycle
Done

2023-04-15 13:43 UTC, danielhollas commented on src/abin.F90
> +   if (ipimd == 5 .and. (nsinglet_lz > 2 .or. ntriplet_lz > 2 )) then
Okay, fair enough, although I am not convinced that this particular warning is more important than other possible warnings. Perhaps in the future we should have some kind of warnings module that would print all warnings at the end of init.

2023-04-15 13:45 UTC, danielhollas commented on src/landau_zener.F90
> +         write (fileunit, '(3ES25.16E3)') en_array_lz(ist, 1), en_array_lz(ist, 2), en_array_lz(ist, 3), en_array_lz(ist, 4)
Okay, cool. It would be nice to add error handling for reading and print a meaningful error, but not neccessary for this PR. I will also have a breaking change to fix restart for FSSH. Perhaps we need some kind of versioning for the restart file to make these kind of changes more explicit.

2023-04-15 13:47 UTC, danielhollas commented on src/landau_zener.F90
> +         if (abs(en_diff(2) * AUTOEV) > deltaE_lz) cycle
Thanks! Though it seems you haven't pushed your changes. btw: please take a look at #160, I need to merge that one first to make the tests work again on Github. Once it is merged, you can either rebase your branch or merge the master into it (`git merge master` or `git rebase master`). In the latter case you would need to force push.

2023-04-17 15:42 UTC, JanosJiri commented on src/landau_zener.F90
> +                if (der_check > 0.3) then
Done

2023-04-17 15:53 UTC, JanosJiri commented on src/landau_zener.F90
> +                    write (*,*) "WARNING, possible discontinuity in PES! Check PES.dat!"
This is a bit problematic since it can be a steep conical intersection. I added a section with another condition, where for change bigger than 130% we set the probability of hopping to 0 artificially because we have an unphysical change of curvature and we have almost certainly a discontinuity.

2023-04-17 16:06 UTC, JanosJiri commented on src/landau_zener.F90
> +         if (abs(en_diff(2) * AUTOEV) > deltaE_lz) cycle
I merged #160 into master, then merged with this branch and pushed here. All the modifications of LZSH are in the 3. commit,

2023-04-17 20:45 UTC, danielhollas requested changes

2023-04-17 20:45 UTC, danielhollas commented on src/landau_zener.F90
> +         if (abs(en_diff(2) * AUTOEV) > deltaE_lz) cycle
@JanosJiri thanks! It looks like the last commit introduced a build failure, can you take a look?

2023-04-17 20:47 UTC, danielhollas commented on src/landau_zener.F90
> +                    write (*,*) "WARNING, possible discontinuity in PES! Check PES.dat!"
Okay, I would personally be more conservative and end stop the simulation for such a large discontinuity, but leaving that up to you.

2023-04-18 12:38 UTC, JanosJiri commented on src/landau_zener.F90
> +         if (abs(en_diff(2) * AUTOEV) > deltaE_lz) cycle
Typo in one variable, now it is fixed and it's working. At least on Krypton.

2023-04-18 20:55 UTC, danielhollas commented
@JanosJiri are you compiling locally with MPI? Looks like the TERAPI-LZ tests are failing.

2023-04-19 14:13 UTC, JanosJiri commented
@danielhollas No, I didn't compile it with MPI. I had general issues with MPI here so I even did not try.

2023-05-22 10:10 UTC, danielhollas commented
@JanosJiri anything I can help with to get this over the finish line?

2023-05-25 13:34 UTC, JanosJiri commented
> @JanosJiri anything I can help with to get this over the finish line?

@danielhollas I know the problem is in the TERAPI-LZ test but I was not able to compile ABIN with MPI here. So I don't see where exactly it failed. I just know it did not hop in the test suite. I will try to compile it again but I won't have time to do it soon.

2023-05-25 14:49 UTC, danielhollas commented
Cool, thanks! In terms of compiling with MPI, I'd recommend using the `dev_scripts/install_mpich.sh` to compile your own MPICH version locally, and then rerunning configure with `./configure --mpi /path/to/mpi`. This is what we use on Github CI so it should work.

2023-06-26 12:54 UTC, danielhollas commented
@JanosJiri I've looked at the failing test `TERAPI-LZ`, and the issue is that in the original test the system hops from 3rd to 2nd state in the third timestep, but with the new code the output in `abin.out` says 

```
 Three-point minimum (03->02) dE/a.u.   4.2773499999952946E-003 Probability:  0.95692859086662962
 ERROR: Change of curvature --> discontinuity in PES!
 Probability set to 0!
```

I am not sure if this is expected, since the PES seems fine to me at first glance. Here are the curves between S2 and S1 states
![image](https://github.com/PHOTOX/ABIN/assets/9539441/b1ec0dad-b9c2-45cd-b4d7-ab7a90325fdf)

Zoomed out view that includes S0

![image](https://github.com/PHOTOX/ABIN/assets/9539441/3c0aab1e-87b6-4dde-880d-70244ef88e2a)

(of course this is a synthetic test but the curves don't seem unrealistic to me)

2023-06-27 06:41 UTC, JanosJiri commented
> @JanosJiri I've looked at the failing test `TERAPI-LZ`, and the issue is that in the original test the system hops from 3rd to 2nd state in the third timestep, but with the new code the output in `abin.out` says
> 
> ```
>  Three-point minimum (03->02) dE/a.u.   4.2773499999952946E-003 Probability:  0.95692859086662962
>  ERROR: Change of curvature --> discontinuity in PES!
>  Probability set to 0!
> ```
> 
> I am not sure if this is expected, since the PES seems fine to me at first glance. Here are the curves between S2 and S1 states ![image](https://user-images.githubusercontent.com/9539441/248800657-b1ec0dad-b9c2-45cd-b4d7-ab7a90325fdf.png)
> 
> Zoomed out view that includes S0
> 
> ![image](https://user-images.githubusercontent.com/9539441/248801343-3c0aab1e-87b6-4dde-880d-70244ef88e2a.png)
> 
> (of course this is a synthetic test but the curves don't seem unrealistic to me)

@danielhollas Thanks for looking at it and also sorry for taking such a long time with it. I believe the problem is in the test, not in the code. The 'smoothness' check I implemented compares the current second derivative of the energy difference with the previous one. However, since this hops on the third step of the algorithm, there is no previous second derivative to compare with. Or rather the 4th energy in the array is still zero generating an artificial second derivative. So I believe this can be solved by adding one more data point before the hopping step. All should be fine then. I will have a look but in a three weeks when I will be back from holidays.

2023-07-19 16:01 UTC, danielhollas commented
@JanosJiri Thanks for fixing the test!

>  I believe the problem is in the test, not in the code. The 'smoothness' check I implemented compares the current second derivative of the energy difference with the previous one. However, since this hops on the third step of the algorithm, there is no previous second derivative to compare with. Or rather the 4th energy in the array is still zero generating an artificial second derivative.

I am not sure I agree that the problem was in the test though (or at least I wouldn't phrase it that way). Before this PR it was perfectly legal to jump on the third step (but not in the first two steps). After this change, we're essentially disallowing any hopping before 4th steps. I guess that is okay, but I am not very happy that there is a misleading warning emitted if the system wants to jump in the third step (i.e. user might think there was discontinuity, even though in reality there wasn't). 

@JanosJiri Let me know your thoughts. I am happy to merge this as is, and we can improve upon this later. :rocket:

2023-07-27 09:51 UTC, JanosJiri commented
> @JanosJiri Thanks for fixing the test!
> 
> > I believe the problem is in the test, not in the code. The 'smoothness' check I implemented compares the current second derivative of the energy difference with the previous one. However, since this hops on the third step of the algorithm, there is no previous second derivative to compare with. Or rather the 4th energy in the array is still zero generating an artificial second derivative.
> 
> I am not sure I agree that the problem was in the test though (or at least I wouldn't phrase it that way). Before this PR it was perfectly legal to jump on the third step (but not in the first two steps). After this change, we're essentially disallowing any hopping before 4th steps. I guess that is okay, but I am not very happy that there is a misleading warning emitted if the system wants to jump in the third step (i.e. user might think there was discontinuity, even though in reality there wasn't).
> 
> @JanosJiri Let me know your thoughts. I am happy to merge this as is, and we can improve upon this later. 🚀

First of all, I agree it is not ideal but there shouldn't be a big problem. The problem is that it won't allow hopping the 2nd step of simulation (not 3rd, 3rd is propagation after hopping) because it has no memory of second derivatives. This should not be a problem when launching the simulations, because in LZ, you should not hop so early, the theory isn't derived for that (it assumes long propagation in the coupling region). The only problem might occur when restarting simulation.

I would merge it and later we can add the second derivative memory to the restart files, which is the only problem I see.

2023-07-27 13:25 UTC, danielhollas approved these changes
Okay, sounds good, thanks @JanosJiri

2023-07-31 21:50 UTC, danielhollas commented
Ugh, I thought I had already merged this. Merging now, apologies for the delay.

2023-07-31 21:53 UTC, merged