NaI analytic potential for FSSH
PHOTOX/ABIN pull request #178
Opened 2024-05-08 13:03 UTC by JanosJiri

Analytic potential for NaI implemented for surface hopping dynamics. The original potential is adiabatic but was adiabatized in the code. Everything even with the source articles is described in the code. 3ps of dynamics can be done in 8 seconds when one is not writing too much on the disk. Accessing the disk is the most demanding part of the simulation. The implementation was compared to the exact QD.
![plot](https://github.com/PHOTOX/ABIN/assets/88504448/b0517d72-2800-480a-890a-8834ca66da18)

2024-05-08 13:52 UTC, danielhollas requested changes
This looks great, amazing work @JanosJiri! :clap: Really excited for this. 

I'll have a closer look at the implementation later, but it looks good overall from high level. 
Thank you for a very clean code and comments. 

Besides some minor stuff I noticed, it would be great if you could add at least one basic test.

Also, please run `./autoformat.py` which should autoformat the code. You might need to split some of the long lines manually, since the formater isn't clever enough for that.

2024-05-08 13:52 UTC, danielhollas commented on src/potentials_sh.F90
> +   ! These articles contain diabatic basis while here we use adiabatic
Could you explain here a bit more how you got from the diabatic to adiabatic parameters?

2024-05-08 13:52 UTC, danielhollas commented on src/potentials_sh.F90
> +! User-definer parameters are set input section 'system'
I think the parameters are currently hard-coded right?
```suggestion
```

2024-05-08 13:52 UTC, danielhollas commented on src/potentials_sh.F90
Let's rename this file to something more specific, like `src/nai_potential.F90`. If we implemented more potentials like this in the future they should go to their own modules.

2024-05-08 13:52 UTC, danielhollas commented on src/surfacehop.F90
> +      if (pot == '_nai_') return ! for NaI model, the couplings are calcualted with forces
```suggestion
      if (pot == '_nai_') return ! for NaI model, the couplings are calculated together with forces
```

2024-05-08 13:52 UTC, danielhollas commented on src/surfacehop.F90
> +         if (pot /= '_tera_' .and. pot /= '_nai_') then
Yeah, this is not great, sorry that you had to deal with this. I'll try to refactor this at some point.

2024-06-05 14:42 UTC, JanosJiri commented
Fprettify applied and one test added. I also processed all the changes requested except for one where I have a question for you. Once we resolve this, the code will be ready for merging.

2024-06-05 17:02 UTC, danielhollas commented on tests/test
I guess this file was added by mistake?

2024-06-05 17:06 UTC, danielhollas commented
Excellent, thanks!

> Fprettify applied and one test added. I also processed all the changes requested except for one where I have a question for you. 

Hmm, I don't see the question anywhere. Did you post it on Github? (Github review UI is sometimes super confusing so perhaps I just missed it)

2024-06-06 09:32 UTC, danielhollas commented
Thanks, the comment is marked as "pending", you'll need to "Finish the review" to publish it. 
I'll answer in the afternoon.

2024-06-06 09:42 UTC, JanosJiri commented on tests/test
Yes.

2024-06-24 06:26 UTC, danielhollas commented on src/potentials_sh.F90
Sorry for a delayed replied. I am on a fence on this --- `potentials.F90` grew over time and contains much simpler potentials. But let's keep the name for now, we can always change it later. Thanks!

2024-06-24 06:45 UTC, danielhollas commented
@JanosJiri apologies for the delay while I was away. This looks really great, thanks for adding a test and extensive comments. Just one question, could you reduce the number of steps in the test? We generally try to keep the number of steps to the absolute minimum for numerical stability, to reduce the chance that the test will break with different compiler versions for example. Also, the test now takes more than 5s, which might not seem like much, but since we have a lot of them it adds up. 

When you modify the `input.in` in the test, you can quickly regenerate the reference files with 

```console
make makeref TEST=SH_NaI
```

In most tests with only do one step. Maybe here we want a bit more so we can test the value of NACM? But I think you anyway see it in `dotprod.dat`, right?

2024-07-03 14:59 UTC, danielhollas approved these changes
:rocket:

2024-07-03 15:01 UTC, merged