LZ with TeraChem over MPI
PHOTOX/ABIN pull request #36
Opened 2020-10-08 11:41 UTC by suchanj

2020-10-08 14:11 UTC, danielhollas requested changes
This looks good, thanks! 

Besides some minor comments, I am mainly concerned about the restart functionality, see my questions below. Ideally, the SH and LZ restarts would be completely separate. Introducing SH section for `_tera_` here would mean that if we would be able to remove it later, it would break existing jobs. Maybe we can discuss in person.

Besides that, I think this would be a good place to introduce some basic tests. Let's discuss tomorrow. Tests specific for `_tera_` will be hard to do because of the MPI so we can do that in a future PR, but we should create basic LZ tests to ensure these changes do not break existing functionality. So ideally you'd create some tests based on the code from `master` (compiled with `-O0`, and then verify that these new tests pass with these changes.

2020-10-08 14:11 UTC, danielhollas commented on landau_zener.F90
> +     call abinerror('lz-QMenergy')
`abinerror` should receive subroutine name, in this case `check_energy_lz`.

2020-10-08 14:11 UTC, danielhollas commented on landau_zener.F90
> +   subroutine lz_rewind(en_array_lz)
Could you please add a comment explaining what this routine does?

2020-10-08 14:21 UTC, danielhollas commented
@suchanj thanks for merging master! Replying to your email here:

1. Codecov seems to be unhappy about the test coverage of the new code. Let's see what happens after adding basic LZ tests. 
I *think* this failure is not blocking merge (it is not "Required", as you can see in the Github UI), but I can also tweak the Codecov config to lower the target for now.

2. Re rebase: Merge commit is okay, but I was also going to suggest a rebase. I agree with keeping the three commits separate. You can force push to an existing PR, no need to create a new one. Thanks!

2020-10-08 14:22 UTC, danielhollas commented
Not sure what the force push would do with the existing review comments. I think they will be fine, but maybe first make the changes and then rebase.

2020-10-08 14:29 UTC, danielhollas commented on analysis.F90
> +   if((ipimd.eq.2).or.(ipimd.eq.5.and.pot.eq.'_tera_'))then
I guess it is needed for initializing SH vars used in `force_terash()`? I think a better approach for now would be to initialize them manually somewhere in the LZ code, since we're already modifying them there.

2020-10-08 16:22 UTC, suchanj commented on analysis.F90
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
I agree with separate restarts, however my main concern is correct passing of wavefunction since LZ is very sensitive to sudden energy jumps, which may appear as false three-point minima. This is all defined in force_terash file so in a manner, it woulde be separate from sh restart section. I wil get rid of this with minor changes.

2020-10-08 16:30 UTC, suchanj commented on analysis.F90
> +        do iw=1,nwalk+1
This only follows a standard initialization prcedure of all arrays:

https://github.com/PHOTOX/ABIN/blob/d039cd4107d5a3815617af063ac02bff2bfb98be/init.F90#L389

2020-10-08 16:31 UTC, danielhollas commented on analysis.F90
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
Oh yeah, definitely, `write_wfn/read_wfn` should stay, but that is called directly from `restout` and does not write to `restart.xyz` but to a separate file.

2020-10-08 16:32 UTC, suchanj commented on analysis.F90
> +   if((ipimd.eq.2).or.(ipimd.eq.5.and.pot.eq.'_tera_'))then
I agree. I will try to move it to the lz_init routine.

2020-10-08 22:13 UTC, danielhollas commented on analysis.F90
> +        do iw=1,nwalk+1
Hmm, I see, we need to fix that, but that's asking for a larger refactor of how we handle these arrays.
Though in principle I think the LZ routines should be using the already existing *_old that are used for the same purpose in SH, if I understand correctly. But let's keep it as is for now, at least before be have robust tests.

2020-10-12 11:07 UTC, suchanj commented on analysis.F90
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
Ok, so omitting the SH parameters from restart file and just performing the read_wfn function is not enough. Apparently, most of the parameters are not actually read from the wfn file during the init routine. Respective variables are not intiialized up until the sh_init routine is called. I can't think of a simple workaround.

2020-10-12 11:14 UTC, danielhollas commented
Isn't the problem that sh_init is trying to read from the restart? Maybe
you could modify it and instead of relaying on global irest parameter, you
could pass irest as a function param to sh_init(), which would be always
false for for LZ case?

Dne po 12. 10. 2020 1:07 odp. uživatel Jiri Suchan <notifications@github.com>
napsal:

> *@suchanj* commented on this pull request.
> ------------------------------
>
> In analysis.F90
> <https://github.com/PHOTOX/ABIN/pull/36#discussion_r503218825>:
>
> > @@ -201,6 +202,7 @@ subroutine restout(x,y,z,vx,vy,vz,time_step)
>     character(len=200)    :: chout, chsystem, chformat
>
>     if(pot.eq.'_tera_'.and.ipimd.eq.2) call write_wfn()
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
>
> Ok, so omitting the SH parameters from restart file and just performing
> the read_wfn function is not enough. Apparently, most of the parameters are
> not actually read from the wfn file during the init routine. Respective
> variables are not intiialized up until the sh_init routine is called. I
> can't think of a simple workaround.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/PHOTOX/ABIN/pull/36#discussion_r503218825>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACIY64P7WFQUSAINIVILC7DSKLPOJANCNFSM4SIUOYSA>
> .
>

2020-10-12 11:21 UTC, danielhollas commented on analysis.F90
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
Okay, strange. Let's then leave as is for now and focus on writing tests. Once we have tests we should definitely refactor this. @suchanj I am currently stack on a delayed train so I'll not make it to the lab today in time. We can discuss tommorow you plan to be there?

2020-10-12 11:39 UTC, suchanj commented on analysis.F90
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
@danielhollas I agree, lets discuss tomorrow. I will try to fix whatever does not need extensive changes and lets setup proper tests first.
(PS: I pinpointed the problem to tocalc matrix, I might be able to fix it afterall? We'll see)

2020-10-12 11:51 UTC, danielhollas commented on analysis.F90
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
Sounds good, thanks!

For the tests, let's compile ABIN with GCC 7 (the one from your bashrc) and with `-O0`.
I don't want to deal with ancient gfortran anymore and I verified that the V7 is available on both ARGON and NEON.

2020-10-13 13:20 UTC, suchanj commented on analysis.F90
> +   if(pot.eq.'_tera_'.and.ipimd.eq.5) call write_wfn()
Ok!
Btw top comment solved (sh restart is now separate), I will force push the commit - lets see if the comments will stick. (I will take few screenshots)

2020-12-15 17:08 UTC, danielhollas requested changes
This looks good! Couple minor comments inline. We can merge after adding tests.

One thing that we should discuss is the default value for the maximum allowed energy jump.

2020-12-15 17:08 UTC, danielhollas commented on landau_zener.F90
> +        !d) Do a verlet step forward from previous position
Any reason why not calling `verletstep()` directly?

2020-12-15 17:08 UTC, danielhollas commented on landau_zener.F90
> +   en_array_lz(:,2) = en_array_lz(:,3)
I think to be on the safe side, `en_array_lz(:,3)` should be overwritten as well, maybe to a zero value?

2020-12-16 11:28 UTC, suchanj commented on landau_zener.F90
> +        !d) Do a verlet step forward from previous position
Good point. Will call it directly.

2020-12-16 11:34 UTC, suchanj commented on landau_zener.F90
> +   en_array_lz(:,2) = en_array_lz(:,3)
Well, not sure about that - in case of error, zero would create artificial three-point miminum whereas en_array_lz(:,2) = en_array_lz(:,3) does not. We can discuss.

2020-12-16 11:51 UTC, suchanj commented on landau_zener.F90
> +   real(DP) :: one=1.0d0, maxEstep=0.1d0 !Maximal energy discontinuity, used in check_energy_lz()
Renamed to "energydifthr_lz", available as an input parameter.

2020-12-16 14:09 UTC, suchanj commented on landau_zener.F90
> +        !d) Do a verlet step forward from previous position
Revised: verletstep() is compiled way at the end, we cannot use the routine

2020-12-16 15:10 UTC, suchanj commented on landau_zener.F90
> +   en_array_lz(:,2) = en_array_lz(:,3)
We concluded this needs to be refactored quite a bit, leaving as is for now.

2020-12-18 13:00 UTC, danielhollas reviewed
Awesome, thanks! I have a couple of very very minor comments. 

One last thing I'd like to discuss before we merge is the default value for the energy jump threshold.

2020-12-18 13:00 UTC, danielhollas commented on TESTS/LZ_SS/input.in
> +nwalk=1,	                	! number of random walkers
Could you please remove unrelated keywords (`nwalk`, `imini`, `istage`).

2020-12-18 13:00 UTC, danielhollas commented on TESTS/LZ_ST/velocities.in
> +
Nit:  delete extra newlines

2020-12-18 13:00 UTC, danielhollas commented on analysis.F90
> +      call lz_restout(102)
:tada:

2020-12-18 13:00 UTC, danielhollas commented on init.F90
> +   namelist /lz/     initstate_lz, nstate_lz, nsinglet_lz, ntriplet_lz, deltaE_lz, energydifthr_lz
Thanks for adding this. :+1:

2020-12-18 13:00 UTC, danielhollas commented on landau_zener.F90
> +        !d) Do a verlet step forward from previous position
@suchanj could you please add this comment explaining why we cannot call `verletstep()` to the code itself? Thanks!

2020-12-18 13:00 UTC, danielhollas commented on landau_zener.F90
> +   en_array_lz(:,2) = en_array_lz(:,3)
Could you add a TODO comment about this? Maybe also comment a bit about why this routine is needed / when is it called. The current one is a bit cryptic to me.

2020-12-18 13:00 UTC, danielhollas commented on landau_zener.F90
> +   !do iat=1,natom
I'd delete this commented code. (also below in `restin()`

2020-12-18 13:00 UTC, danielhollas commented on landau_zener.F90
> +   real(DP) :: energydifthr_lz=0.5d0 !Maximum energy difference (eV) between two consecutive steps, used in check_energy_lz()
`0.5 eV` seems extremely lax to me. Maybe we can discussed in person?

2020-12-18 13:00 UTC, danielhollas commented on TESTS/LZ_SS/MOLPRO/r.molpro
> +#!/bin/bash
Maybe I would generally rename this to `MOLPRO-LZ` (same as in surface hopping we typically use `MOLPRO-SH`.

2020-12-18 14:55 UTC, suchanj commented on landau_zener.F90
> +   real(DP) :: energydifthr_lz=0.5d0 !Maximum energy difference (eV) between two consecutive steps, used in check_energy_lz()
I have seen changes for triplet states energies in magnitude up to 1.0 eV for cytosine molecule. We can discuss.

2020-12-18 15:43 UTC, danielhollas approved these changes

2020-12-18 15:56 UTC, suchanj commented
Major LZ refactor, tests and credible restart capability

2020-12-18 15:56 UTC, merged